/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToCompareRouteImport } from './routes/to-compare'
import { Route as TalentPoolRouteImport } from './routes/talent-pool'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'

const ToCompareRoute = ToCompareRouteImport.update({
  id: '/to-compare',
  path: '/to-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentPoolRoute = TalentPoolRouteImport.update({
  id: '/talent-pool',
  path: '/talent-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/talent-pool': typeof TalentPoolRoute
  '/to-compare': typeof ToCompareRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/talent-pool': typeof TalentPoolRoute
  '/to-compare': typeof ToCompareRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/talent-pool': typeof TalentPoolRoute
  '/to-compare': typeof ToCompareRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/talent-pool' | '/to-compare' | '/matches/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/talent-pool' | '/to-compare' | '/matches/$matchId'
  id: '__root__' | '/' | '/talent-pool' | '/to-compare' | '/matches/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TalentPoolRoute: typeof TalentPoolRoute
  ToCompareRoute: typeof ToCompareRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/to-compare': {
      id: '/to-compare'
      path: '/to-compare'
      fullPath: '/to-compare'
      preLoaderRoute: typeof ToCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-pool': {
      id: '/talent-pool'
      path: '/talent-pool'
      fullPath: '/talent-pool'
      preLoaderRoute: typeof TalentPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TalentPoolRoute: TalentPoolRoute,
  ToCompareRoute: ToCompareRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
